FROM node:20.12.0-alpine3.19
WORKDIR /usr/src/app

COPY package*. turbo.json tsconfig.json ./

COPY packages ./packages
COPY apps ./app
# copies everything but run only backend

RUN npm install
RUN npm run db:generate
RUN npm run build
EXPOSE 3003
CMD ["npm", "run", "start-bank-webhook"]
