FROM node:20.12.0-alpine3.19
WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY packages ./packages
COPY apps ./apps
# copies everything but run only merchant-app

RUN npm install
RUN npm run db:generate
RUN npm run build
CMD [ "npm", "run", "start-merchant-app" ]